version: "3"
services:
  cypress:
    build:
      context: .
      dockerfile: Dockerfile-cypress
    volumes:
      - node_modules:/app/node_modules
      - cypress_cache:/root/.cache/Cypress/
    image: project-cypress
  test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - cypress
    environment:
      - "NODE_ENV=development"
    volumes:
      - node_modules:/app/node_modules
      - cypress_cache:/root/.cache/Cypress/
volumes:
  node_modules:
  cypress_cache:
